version: '3.8'

networks:
  webbanlinhkien:

volumes:
  mysql_data:
  nginx_data:
  letsencrypt_data:

services:
  database-mysql:
    image: mysql-database-image
    build: ./Database-MySql
    container_name: mysql-database-container
    networks:
      - webbanlinhkien
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: WebBanLinhKien
      MYSQL_SQL_MODE: "NO_ENGINE_SUBSTITUTION"
    volumes:
      - mysql_data:/var/lib/mysql

  user-wblk:
    image: user-wblk-image
    build: ./User-WBLK
    container_name: user-wblk-container
    networks:
      - webbanlinhkien
    ports:
      - "5124:5124"
      - "7050:7050"
    depends_on:
      - database-mysql
    environment:
      - ASPNETCORE_URLS=http://+:5124

  admin-wblk:
    image: admin-wblk-image
    build: ./Admin-WBLK
    container_name: admin-wblk-container
    networks:
      - webbanlinhkien
    ports:
      - "5177:5177"
      - "7012:7012"
    depends_on:
      - database-mysql
    environment:
      - ASPNETCORE_URLS=http://+:5177

  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - nginx_data:/data
      - letsencrypt_data:/etc/letsencrypt
    networks:
      - webbanlinhkien
